# -*- coding: utf-8 -*-
"""random movement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fM4PCXQiCj-tvONrRZunbZRnisXI4VVP
"""

import numpy as np
import matplotlib.pyplot as plt

# Parameters
n_steps = 1000  # Number of steps in the random walk

# Simulate 1D random walk
steps = np.random.choice([-1, 1], size=n_steps)  # Choose -1 (left) or 1 (right) randomly
position = np.cumsum(steps)  # Cumulative sum gives the position at each step

# Plot the random walk
plt.figure(figsize=(10, 5))
plt.plot(position, label="1D Random Walk")
plt.title("1D Random Walk Simulation")
plt.xlabel("Step")
plt.ylabel("Position")
plt.legend()
plt.show()